source 'http://rubygems.org'

gem 'rake', '~> 10.4'
gem 'cucumber', '~> 1.3'
gem 'rspec', '~> 3.1'
gem 'capybara', '~> 2.4'
gem 'site_prism', '~> 2.0'
gem 'activesupport', '~> 4.2'
gem 'tzinfo', '~> 1.0'
gem 'headless', '~> 1.0'
gem 'selenium-webdriver', '~> 2.44'
gem 'capybara-user_agent', '~> 0.0.3'
gem 'capybara-iphone', '~> 0.2.0'
gem 'facter', '~> 2.3'
gem 'parallel_tests', '~> 1.0.6'
gem 'sauce', '~> 3.5'
gem 'sauce-connect'
gem 'cucumber-rails'
gem 'sauce-cucumber'