source 'http://rubygems.org'

gem 'rake', '~> 10.1'
gem 'cucumber', '~> 1.3'
gem 'rspec', '~> 2.0'
gem 'capybara', '~> 2.3.0'
gem 'site_prism', '~> 2.0'
gem 'activesupport', '~> 4.1'
gem 'tzinfo', '~> 1.2'
gem 'headless', '~> 1.0.1'
gem 'selenium-webdriver', '~> 2.0'
gem 'capybara-user_agent', '~> 0.0.2'
gem 'capybara-iphone', '~> 0.2.0'
gem 'facter', '~> 2.1'
gem 'parallel_tests', '= 0.15.0'
gem 'sauce', '~> 3.1.1'
gem 'sauce-connect'
gem 'cucumber-rails'
gem 'sauce-cucumber'