##############################
### Configuration defaults ###
##############################
defaults: &execution_defaults
  # Default Configuration to run (Environment)
  default_config: 'default_env'
  # Default TimeOuts for tests (sec).
  # You can add any timeouts and use them within tests anywhere you need.
  # Add method(s) into ../aglet/ext/laces.rb to be able
  # to retrieve this value(s) within tests afterwards.
  ajax_timeout: '10'
  front_timeout: '30'
  back_timeout: '30'

##############################
###   Environment Config   ###
##############################
default_env:
  <<: *execution_defaults
  language_id: INT
  default_wait_time: '2'
  site_root: http://www.keep.google.com

##############################
### Configuration Template ###
##############################
#environment_name:
#  <<: *execution_defaults
#  # Website Name / Language ID
#  language_id: USA
#  #Capybara Default TimeOut
#  default_wait_time: 2
#  #URL
#  site_root: http://www.something.com